### parameter related to the mqtt server
mqtt:
  host: <mqqt_host>
  # port: 1883
  user: <mqtt_user>
  password: <mqtt_password>
  # client_id:
  # base_topic: gpio2mqtt
  # homeassistant_topic: homeassistant

### list of devices
devices:
  - id: <unique id>
    name: <unique name>
    type: <PulseCounter|ElectricityPulseMeter>
    # homeassistant_discovery: true
    gpio_pin: <pin>
    active_high: <true|false>
    # init_mode: <new|mqtt>
    # publish_interval_seconds: 0
    # pulses_per_kwh: <pulse_per_kwz>
