### parameter related to the mqtt server
mqtt:
  ### host name or ip address
  host: <mqqt_host>
  ### port number
  # port: 1883
  ### base topic used for device states
  # base_topic: gpio2mqtt
  ### user
  user: <mqtt_user>
  ### password
  password: <mqtt_password>
  ### client id to use for the connection
  # client_id:

### list of devices
devices:
    ### device id, also used to build mqtt topics, must be unique within gpio2mqtt
  - id: <unique id>
    ### friendly device name, must be unique within gpio2mqtt
    name: <unique name>
    ### device type, allowed values are:
    ### PulseCounter: counts high or low pulses, publishes total count and delta in intervals
    ### ElectricityPulseMeter: pulse counter based electricity meter, additionbally publishes energy and power
    type: <type>
    ### (PulseCounter, ElectricityPulseMeter); pgio pin (BCM) to use
    gpio_pin: <pin>
    ### (PulseCounter, ElectricityPulseMeter); true to handle high input as active (raising edge), false to handle low input as active (falling edge)
    active_high: <true|false>
    ### (PulseCounter, ElectricityPulseMeter); how to init the last state; "new" or not set to start with zero, "mqtt" to fetch last state from mqtt state topic
    #init_mode: new
    ### (PulseCounter, ElectricityPulseMeter); minimum publish interval in seconds, at least one pulse must be counted to trigger publish
    # publish_interval_seconds: 0
    ### (ElectricityPulseMeter); number of pulses for 1 kWh
    pulses_per_kwh: <pulse_per_kwz>
